name: Sync Fork and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # 每24小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Sync fork
        run: |
          git remote add upstream https://github.com/DokeyAI/dokeyai-data.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
